#!/bin/bash
#
# Заменитель chmod для изменения прав доступа к файлу в распакованном образе.
# Права доступа заменяются в файле {название раздела}_statfile.txt.
#

MODE=$1
FILE="$2"

if test -z "$FILE" ; then
	echo "Меняет права доступа к файлу в распакованном образе ext4"
	echo "Запуск: $0 [числовой режим доступа] [файл]"
	exit 1
fi

if ! test -e "$FILE" ; then
	echo "$0: файл $FILE не существует"
	exit 1
fi

# Идём вверх по иерархии файлов, пока не найдём файл [имя раздела]_statfile.txt
FILE=$(readlink -f "$FILE")
CUR="$FILE"
while true; do
	DIR=$(dirname "$CUR")
	NAME=$(basename "$CUR")
	STATS="$DIR/${NAME}_statfile.txt"
	test -e "$STATS" && break

	if test "$DIR" = "/" ; then
		echo "$0: не удалось найти файл ${NAME}_statfile.txt"
		exit 1
	fi

	CUR="$DIR"
done

DIR="$DIR/$NAME"

# Оставить имя файла относительно корня файловой системы
FILE="${FILE/${DIR}\/}"

if ! test -e "$DIR/$FILE" ; then
	echo "$0: ошибка определения относительного пути $FILE"
	exit -1
fi

awk -v FILE="$NAME/$FILE" -v MODE="$MODE" '
$1 == FILE {
	print $1" "$2" "$3" "MODE
	REPLACED="Y"
	next
}

{ print }

END {
	if (REPLACED == "") print FILE" 0 0 "MODE
}' "$STATS" > "${STATS}.new"

mv -f "${STATS}.new" "$STATS"
