#!/bin/bash
#
# Утилита для создания пакетов обновления прошивки через Recovery
#
# Запуск: upd-maker <название> <ro.product.device> <update.zip> [образы разделов...]
#
# <название> задаёт название, которое будет отображаться во время
# обновления прошивки (название пакета обновления).
#
# <ro.product.device> задаёт имя аппаратной платформы, для которой
# предназначен этот пакет. На текущий момент проверка названия платформы
# отключена, но это может измениться.
#
# Название файла (без расширения) с образом раздела должно быть
# таким же, как название устройства /dev/block/*. Единственное исключение -
# раздел _aml_dtb, который записывается в /dev/dtb.
#
# Образ раздела должен быть ровно в том виде, в котором он записывается
# в раздел! В частности, sparse ext4 образы должны быть быть
# предварительно распакованы (например, утилитой simg2img)
#

NAME="$1"
DEV="$2"
UPD=$(readlink -m "$3")
shift 3
FILES=$*

if [ -z "$FILES" ] ; then
	echo "Запуск: upd-maker <название прошивки> <ro.product.device> <update.zip> <образы разделов...>"
	exit 1
fi

DIR=$(dirname $(readlink -f $0))
UPD_DIR="$(dirname "$UPD")/update"
UPD_SCR="$UPD_DIR/META-INF/com/google/android/updater-script"

set -e

echo "Создаём сценарий для update-binary ..."
rm -rf "$UPD_DIR"
mkdir -p "$UPD_DIR"
unzip -q "$DIR/upd-maker-template.zip" -d "$UPD_DIR"
mkdir -p "$UPD_DIR/META-INF/com/android"
echo "pre-device=$DEV" > "$UPD_DIR/META-INF/com/android/metadata"

# Не проверяем на правильное название платформы...
# иначе пользователь не сможет откатиться этим пакетом после "чужих" прошивок.
#cat >> "$UPD_SCR" <<EOF
#product=\`cat /*.prop | sed -ne '/ro.product.device *=/{' -e 's/.*=//' -e p -e '}'\`
#if test "\$product" != "$DEV" ; then
#	ui_print "Package is for product $DEV, not for \$product"
#	exit 1
#fi
#EOF
echo "ui_print \"Installing -=<( $NAME )>=-\"" >> "$UPD_SCR"

for x in $FILES ; do
	file="$(basename "$x")"
	part="$(basename $(basename "$x" .PARTITION.raw) .PARTITION)"
	test "$UPD_DIR/$file" -ot "$x" && cp -a "$x" "$UPD_DIR/$file"
	dev="/dev/block/$part"
	desc="partition '$part'"
	if [ "$part" == "_aml_dtb" ] ; then
		# Special case for AMLogic dtb partition
		dev="/dev/dtb"
		desc="Device Tree"
	fi
	cat >> "$UPD_SCR" <<EOF
ui_print " - Flashing $desc"
if ! package_extract_file $file $dev ; then
	ui_print "Failed to extract $file to $dev"
	exit 1
fi
EOF
done

echo "ui_print \"Success!\"" >> "$UPD_SCR"

echo "Создание промежуточного архива ..."
rm -f "${UPD}~"
(cd "$UPD_DIR"; zip -qr "${UPD}~" .)

echo "Подписываем архив тестовым ключом ..."
java -jar "$DIR/zipsigner-3.0.jar" "${UPD}~" "${UPD}"
rm -f "${UPD}~"

echo "Готово"
