#!/bin/sh

set -e

../tools/upd-maker -n "vendor-system `date '+%x %X'`" -d u211 -o update-vendor-system.zip \
	../out/x96max/beelink/img-ubt/vendor.PARTITION.raw \
	../out/x96max/beelink/img-ubt/system.PARTITION.raw

rm -rf update
