#!/bin/sh

set -e

cd ..

PART="out/x96max/beelink/4G/img-ubt/vendor.PARTITION.raw \
      out/x96max/beelink/4G/img-ubt/system.PARTITION.raw"

make ubt-img
make $PART

tools/upd-maker -n "vendor-system `date '+%x %X'`" -d u211 -o update-vendor-system.zip \
	$PART

rm -rf update
